###############################################################################
# DPS8M Proxy - .github/dependabot.yml
# Copyright (c) 2025-2026 Jeffrey H. Johnson
# Copyright (c) 2025-2026 The DPS8M Development Team
# SPDX-License-Identifier: MIT-0
# scspell-id: 825ba9de-6bd2-11f0-af76-80ee73e9b8e7
###############################################################################

version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
